### ISSUE TITLE
the player is not teleported to the end

### ISSUE THREAD

**Issue by feanchy** [KCodeYT/VanillaGenerator#22]
when entering the end portal, the player has infinite landscape generation, everything is fine with the rest of the worlds
![Снимок экрана 2022-10-07 231256](https://user-images.githubusercontent.com/50043944/194645960-2943e2ad-6e9a-44ae-a392-6f57bebeb0a3.png)

**Comment by KCodeYT** [comment]
This is fixed in the 0.0.12-SNASHOT update which can be downloaded from [here](https://github.com/KCodeYT/VanillaGenerator/releases/tag/0.0.12-SNAPSHOT)
