### ISSUE TITLE
Chunks in dimension based worlds do not generate.

### ISSUE THREAD

**Issue by CoolLoong** [KCodeYT/VanillaGenerator#6]

**Comment by KCodeYT** [comment]
Hey have you made sure that every server is started?
The plugin sends a message in the console for ensurance.
The message should look like the following:
"[VanillaGeneratorPlugin]: Level nether successfully connected!"

**Comment by KCodeYT** [comment]
This issue appears to have something to do with movement as the bots somehow cant move anymore when they switched dimensions. Im trying to fix this issue currently but do not know how, so this can take its time.

**Comment by KCodeYT** [comment]
This issue should be resolved with the 0.0.6-SNAPSHOT update! Thanks for helping out!
