### ISSUE TITLE
spawn without mobs

### ISSUE THREAD

**Issue by feanchy** [KCodeYT/VanillaGenerator#7]
I have a spawner without mods, mobiplugin plugins, what is the problem
![Снимок экрана 2022-06-15 122602](https://user-images.githubusercontent.com/50043944/173793957-e42dbda6-b9f3-4945-975b-9659b075e010.png)
?

**Comment by MonoAdrian23** [comment]
Use MobPlugin from Cloudburst

**Comment by feanchy** [comment]
> Используйте MobPlugin от Cloudburst

lol, the mobs in the background don't say anything?! Of course I use this plugin

**Comment by KCodeYT** [comment]
Hey,

Please read this message as I think it has the same reason: https://github.com/KCodeYT/VanillaGenerator/issues/8#issuecomment-1159400833

**Comment by KCodeYT** [comment]
This issue should be fixed with the 0.0.5-SNAPSHOT update.
