### ISSUE TITLE
there are no mobs in the dungeons, or in the spawners, anywhere!!!

### ISSUE THREAD

**Issue by feanchy** [KCodeYT/VanillaGenerator#8]
there are no mobs in the dungeons, or in the spawners, anywhere!!!

**Comment by KCodeYT** [comment]
Hey this plugin is only a generator and not a plugin which adds mobs to the powernukkitx server environment, Im sorry for that but for that purpose there are plugins like MobPlugin which can downloaded from the [cloudburst resources page](https://cloudburstmc.org/resources/mobplugin.3/).

Mobs in Spawners are planned to be implemented in this generator, but Im waiting for powernukkitx to add the block entity for it, so this generator can convert the spawner to powernukkitx.

**Comment by feanchy** [comment]
> Эй, этот плагин является только генератором, а не плагином, который добавляет мобов в серверную среду powernukkitx. Мне очень жаль, но для этой цели есть плагины, такие как MobPlugin, которые можно загрузить со [страницы ресурсов Cloudburst](https://cloudburstmc.org/resources/mobplugin.3/) .
> 
> В этом генераторе планируется реализовать мобов в Спаунерах, но я жду, пока powernukkitx добавит для него блочную сущность, чтобы этот генератор мог преобразовать спавнера в powernukkitx.

in plugins from wode there is no such problem, spawners function normally, mobs corresponding to the building spawn near villages and other buildings, and I also use the plugin MobPlugin

**Comment by KCodeYT** [comment]
Yea, this plugin works a little bit different then the plugins of wode.

**Comment by KCodeYT** [comment]
This issue should be fixed with the 0.0.5-SNAPSHOT update.
